const storageKey = 'rhythm-foundation-v2';
const today = new Date();
const dateKey = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const todayKey = dateKey(today);
const defaultData = { points: 65, completed: { [todayKey]: ['water', 'plan'], [dateKey(new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1))]: ['water', 'plan', 'walk', 'read'], [dateKey(new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2))]: ['water', 'plan', 'walk'] }, routines: [ { id: 'morning', name: 'Morning reset', icon: '☀', color: '#fff0b5', bonus: 20, habits: [ { id: 'water', name: 'Drink a glass of water', note: 'Start gently', points: 10, schedule: { type: 'daily' } }, { id: 'plan', name: 'Set your top 3 priorities', note: '5 minutes of focus', points: 15, schedule: { type: 'daily' } }, { id: 'walk', name: 'Move your body', note: 'A 10-minute walk counts', points: 15, schedule: { type: 'weekly', target: 3 } } ] }, { id: 'evening', name: 'Evening wind-down', icon: '☾', color: '#dfd2ff', bonus: 25, habits: [ { id: 'read', name: 'Read for 10 minutes', note: 'One page is enough to begin', points: 15, schedule: { type: 'weekly', target: 4 } }, { id: 'reflect', name: 'Write one line of reflection', note: 'Notice what felt good', points: 10, schedule: { type: 'daily' } }, { id: 'screen', name: 'Put your phone away', note: '30 minutes before sleep', points: 20, schedule: { type: 'weekly', target: 5 } } ] } ] };
let data = JSON.parse(localStorage.getItem(storageKey) || localStorage.getItem('rhythm-foundation-v1') || 'null') || JSON.parse(JSON.stringify(defaultData));
let currentView = 'today';
let historyDate = new Date(today);
const $ = (selector) => document.querySelector(selector);
const colors = ['#fff0b5', '#dfd2ff', '#c9ebff', '#ffd5c5', '#d6f0bd'];
function normalize() { const starterTargets = { walk: 3, read: 4, screen: 5 }; const needsMigration = !data.version; data.reflections ||= {}; data.routines.forEach((routine, index) => { routine.habits ||= []; routine.color ||= colors[index % colors.length]; routine.icon ||= '✦'; routine.bonus ||= 20; routine.archived ||= false; routine.habits.forEach((habit) => { if (!habit.schedule || (needsMigration && starterTargets[habit.id])) habit.schedule = starterTargets[habit.id] ? { type: 'weekly', target: starterTargets[habit.id] } : { type: 'daily' }; habit.archived ||= false; }); }); data.version = 2; }
normalize();
function save() { localStorage.setItem(storageKey, JSON.stringify(data)); }
function escapeHTML(value) { const node = document.createElement('div'); node.textContent = value; return node.innerHTML; }
function allHabits(includeArchived = false) { return data.routines.filter((routine) => includeArchived || !routine.archived).flatMap((routine) => routine.habits.filter((habit) => includeArchived || !habit.archived).map((habit) => ({ ...habit, routine }))); }
function todayCompleted() { return new Set(data.completed[todayKey] || []); }
function completedFor(date) { return new Set(data.completed[date] || []); }
function weekStart(reference = today) { const value = new Date(reference); value.setHours(0, 0, 0, 0); value.setDate(value.getDate() - ((value.getDay() + 6) % 7)); return value; }
function weekKeys(reference = today) { const first = weekStart(reference); return Array.from({ length: 7 }, (_, index) => { const date = new Date(first); date.setDate(first.getDate() + index); return dateKey(date); }); }
function weeklyCount(habit, reference = today) { return weekKeys(reference).reduce((total, key) => total + (completedFor(key).has(habit.id) ? 1 : 0), 0); }
function weeklyGoalDone(habit) { return weeklyCount(habit) >= habit.schedule.target; }
function statusFor(habit) { return habit.schedule.type === 'weekly' ? weeklyGoalDone(habit) : todayCompleted().has(habit.id); }
function dailyPercent(date) { const daily = allHabits().filter((habit) => habit.schedule.type === 'daily'); const completed = completedFor(date); return daily.length ? Math.round(daily.filter((habit) => completed.has(habit.id)).length / daily.length * 100) : 0; }
function weekDates() { return weekKeys().map((key) => new Date(`${key}T12:00:00`)); }
function currentStreak() { let streak = 0; const cursor = new Date(today); while (completedFor(dateKey(cursor)).size) { streak += 1; cursor.setDate(cursor.getDate() - 1); } return streak; }
function level() { return Math.floor(data.points / 100) + 1; }
function levelTitle(value) { return value < 2 ? 'Fresh start' : value < 4 ? 'Finding flow' : value < 7 ? 'Steady rhythm' : 'Habit architect'; }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timeout); showToast.timeout = setTimeout(() => toast.classList.remove('show'), 2600); }
function scheduleText(habit) { return habit.schedule.type === 'daily' ? 'Every day' : `${habit.schedule.target}× per week · flexible`; }
function renderHeader() { const value = level(); const remainder = data.points % 100; $('#dateLabel').textContent = new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric' }).format(today).toUpperCase(); $('#levelValue').textContent = value; $('#levelName').textContent = levelTitle(value); $('#pointsValue').textContent = data.points; $('#levelFill').style.width = `${remainder}%`; $('#nextLevelLabel').textContent = `${100 - remainder || 100} to level ${value + 1}`; $('#sideStreak').textContent = `${currentStreak()} day${currentStreak() === 1 ? '' : 's'}`; }
function renderWeek() { const days = weekDates(); const labels = ['M', 'T', 'W', 'T', 'F', 'S', 'S']; const daily = allHabits().filter((habit) => habit.schedule.type === 'daily'); const weekly = allHabits().filter((habit) => habit.schedule.type === 'weekly'); const total = daily.length * 7 + weekly.reduce((sum, habit) => sum + habit.schedule.target, 0); const achieved = days.reduce((sum, date) => sum + daily.filter((habit) => completedFor(dateKey(date)).has(habit.id)).length, 0) + weekly.reduce((sum, habit) => sum + Math.min(weeklyCount(habit), habit.schedule.target), 0); const score = total ? Math.round(achieved / total * 100) : 0; const weekCard = $('.week-card'); weekCard.classList.remove('score-red', 'score-orange', 'score-green'); weekCard.classList.add(score < 34 ? 'score-red' : score < 67 ? 'score-orange' : 'score-green'); $('#weekDays').innerHTML = days.map((date, index) => { const key = dateKey(date); const isToday = key === todayKey; const done = completedFor(key).size > 0; return `<div class="day ${done ? 'done' : ''} ${isToday ? 'today' : ''}"><span>${labels[index]}</span><i class="day-dot">${done ? '✓' : ''}</i></div>`; }).join(''); $('#weeklyScore').textContent = `${score}%`; $('#weekCopy').textContent = score ? `You’ve kept ${score}% of your promises to yourself.` : 'A new week is a new chance to find your rhythm.'; }
function habitMarkup(habit) { const checked = todayCompleted().has(habit.id); const weekly = habit.schedule.type === 'weekly'; const count = weeklyCount(habit); const goalMet = weekly && count >= habit.schedule.target; const detail = weekly ? `${Math.min(count, habit.schedule.target)} / ${habit.schedule.target} this week${goalMet ? ' · goal met' : ''}` : habit.note; const reflectionAction = habit.id === 'reflect' ? `<button class="reflection-entry" data-reflection-entry="today">${data.reflections[todayKey] ? 'Edit reflection' : 'Write reflection'}</button>` : ''; return `<div class="habit ${checked ? 'done' : ''}"><button class="check" data-habit="${habit.id}" aria-label="Toggle ${escapeHTML(habit.name)}">${checked ? '✓' : ''}</button><div><p class="habit-name">${escapeHTML(habit.name)}</p><p class="habit-description ${goalMet ? 'goal-met' : ''}">${escapeHTML(detail)}</p>${reflectionAction}</div><span class="habit-points">+<b>${habit.points}</b>${weekly ? '<small> flexible</small>' : ''}</span></div>`; }
function renderRoutines() { const completed = todayCompleted(); let total = 0; let done = 0; $('#routineList').innerHTML = data.routines.filter((routine) => !routine.archived).map((routine) => { const habits = routine.habits.filter((habit) => !habit.archived); const routineDone = habits.filter(statusFor).length; total += habits.length; done += routineDone; const ready = habits.length && routineDone === habits.length; return `<article class="routine" style="--icon-bg:${routine.color}"><header class="routine-heading"><div class="routine-icon">${routine.icon}</div><div class="routine-info"><h3>${escapeHTML(routine.name)}</h3><p>${routineDone} of ${habits.length} goals complete</p></div><span class="routine-reward">+<b>${routine.bonus}</b> completion bonus</span><button class="routine-complete" data-routine="${routine.id}" ${ready ? '' : 'disabled'}>Collect bonus</button></header>${habits.map(habitMarkup).join('') || '<p class="empty-routine">No active habits in this routine.</p>'}</article>`; }).join(''); const percent = total ? Math.round(done / total * 100) : 0; $('#todayProgress').textContent = `${done} / ${total} goals complete`; $('#dailyFill').style.width = `${percent}%`; $('#doneMessage').hidden = done !== total || !total; $('#heroCopy').textContent = percent === 100 ? 'You completed every promise you made to yourself today.' : percent >= 50 ? 'You’re in motion. Keep the gentle momentum going.' : 'Your routines are waiting. Let’s make today matter.'; }
function renderManager() { const routines = data.routines.filter((routine) => !routine.archived); $('#manageRoutines').innerHTML = routines.map((routine) => `<div class="manage-routine"><span style="background:${routine.color}">${routine.icon}</span><strong>${escapeHTML(routine.name)}</strong><button data-archive-routine="${routine.id}">Archive routine</button></div>`).join(''); $('#manageList').innerHTML = allHabits().map((habit) => `<div class="manage-item" style="--accent:${habit.routine.color}"><i class="manage-dot"></i><div><strong>${escapeHTML(habit.name)}</strong><span>${escapeHTML(habit.routine.name)} · ${scheduleText(habit)}</span></div><button class="manage-edit" data-edit="${habit.id}">Edit</button><button class="manage-archive" data-archive="${habit.id}">Archive</button></div>`).join('') || '<p class="manager-copy">Add your first habit to get started.</p>'; }
function renderArchived() { const archivedRoutines = data.routines.filter((routine) => routine.archived).map((routine) => ({ type: 'routine', id: routine.id, name: routine.name, detail: `${routine.habits.length} habits` })); const archivedHabits = data.routines.filter((routine) => !routine.archived).flatMap((routine) => routine.habits.filter((habit) => habit.archived).map((habit) => ({ type: 'habit', id: habit.id, name: habit.name, detail: routine.name }))); const items = [...archivedRoutines, ...archivedHabits]; $('#archiveCount').textContent = `${items.length} item${items.length === 1 ? '' : 's'}`; $('#archivedList').innerHTML = items.length ? items.map((item) => `<div class="archived-item"><i></i><div><strong>${escapeHTML(item.name)}</strong><small>${escapeHTML(item.detail)}</small></div><button data-restore-type="${item.type}" data-restore-id="${item.id}">Restore</button></div>`).join('') : '<p class="empty-archive">Nothing is archived right now.</p>'; }
function renderReflection() { const entry = data.reflections[todayKey]; $('#reflectionTitle').textContent = entry ? 'A note to your future self.' : 'Leave yourself a note.'; $('#reflectionPreview').textContent = entry || 'A single honest line is enough.'; $('#openReflection').textContent = entry ? 'Edit reflection' : 'Write a reflection'; }
function openReflection(date = today) { const key = dateKey(date); $('#reflectionDate').textContent = new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric' }).format(date); $('#reflectionText').value = data.reflections[key] || ''; $('#reflectionModal').dataset.date = key; $('#reflectionModal').showModal(); setTimeout(() => $('#reflectionText').focus(), 20); }
function dailyHabitStreak(habit) { let count = 0; const cursor = new Date(today); while (completedFor(dateKey(cursor)).has(habit.id)) { count += 1; cursor.setDate(cursor.getDate() - 1); } return count; }
function weeklyHabitStreak(habit) { let count = 0; let cursor = weekStart(); while (true) { const keys = weekKeys(cursor); const completions = keys.filter((key) => completedFor(key).has(habit.id)).length; if (completions < habit.schedule.target) break; count += 1; cursor.setDate(cursor.getDate() - 7); } return count; }
function renderInsights() { const habits = allHabits(); const daily = habits.filter((habit) => habit.schedule.type === 'daily'); const weekly = habits.filter((habit) => habit.schedule.type === 'weekly'); const days = weekDates(); const dailyActions = days.reduce((sum, date) => sum + daily.filter((habit) => completedFor(dateKey(date)).has(habit.id)).length, 0); const weeklyActions = weekly.reduce((sum, habit) => sum + Math.min(weeklyCount(habit), habit.schedule.target), 0); const possible = daily.length * 7 + weekly.reduce((sum, habit) => sum + habit.schedule.target, 0); const score = possible ? Math.round((dailyActions + weeklyActions) / possible * 100) : 0; const weeklyGoals = weekly.filter(weeklyGoalDone); const bestIndex = days.reduce((best, date, index) => completedFor(dateKey(date)).size > completedFor(dateKey(days[best])).size ? index : best, 0); const bestDate = days[bestIndex]; const dayName = new Intl.DateTimeFormat('en-US', { weekday: 'long' }).format(bestDate); const shortLabels = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'];
  $('#insightScore').textContent = `${score}%`; $('#insightCompletions').textContent = dailyActions + weeklyActions; $('#insightBestDay').textContent = completedFor(dateKey(bestDate)).size ? dayName : '—'; $('#insightBestDayCopy').textContent = completedFor(dateKey(bestDate)).size ? `${completedFor(dateKey(bestDate)).size} actions completed` : 'your week is just starting'; $('#insightGoals').textContent = `${weeklyGoals.length} / ${weekly.length}`;
  $('#weeklyChart').innerHTML = days.map((date, index) => { const amount = daily.length ? Math.round(daily.filter((habit) => completedFor(dateKey(date)).has(habit.id)).length / daily.length * 100) : 0; return `<div class="chart-day ${dateKey(date) === todayKey ? 'today' : ''}"><strong>${amount ? `${amount}%` : ''}</strong><div class="chart-track"><i class="chart-fill" style="height:${amount}%"></i></div><span>${shortLabels[index]}</span></div>`; }).join('');
  $('#habitInsights').innerHTML = habits.map((habit) => { const weeklyGoal = habit.schedule.type === 'weekly'; const progress = weeklyGoal ? Math.min(100, Math.round(weeklyCount(habit) / habit.schedule.target * 100)) : Math.round(days.filter((date) => completedFor(dateKey(date)).has(habit.id)).length / 7 * 100); const streak = weeklyGoal ? weeklyHabitStreak(habit) : dailyHabitStreak(habit); const unit = weeklyGoal ? `successful week${streak === 1 ? '' : 's'}` : `day${streak === 1 ? '' : 's'} in a row`; const secondary = weeklyGoal ? `${weeklyCount(habit)} of ${habit.schedule.target} this week` : `${days.filter((date) => completedFor(dateKey(date)).has(habit.id)).length} of 7 days this week`; return `<article class="habit-insight"><i class="habit-ring" style="--ring:${habit.routine.color}">${progress}%</i><div><strong>${escapeHTML(habit.name)}</strong><p>${secondary}</p></div><span>${streak} ${unit}</span></article>`; }).join('');
  const note = weekly.length && weeklyGoals.length === weekly.length ? 'You met every flexible weekly goal. That is consistency built around real life, not rigid rules.' : weeklyGoals.length ? `You met ${weeklyGoals.length} flexible weekly goal${weeklyGoals.length === 1 ? '' : 's'} already. Keep the remaining goals light and doable.` : score ? 'Your progress is accumulating. Focus on one next action rather than trying to catch up on everything.' : 'Start with the smallest habit on your list. A completed first step gives the week somewhere to grow.'; $('#insightNote').querySelector('p').textContent = note;
}
function renderHistory() { const key = dateKey(historyDate); const completed = completedFor(key); const isToday = key === todayKey; const completedCount = completed.size; const entry = data.reflections[key]; $('#historyDateLabel').textContent = new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric' }).format(historyDate); $('[data-history-nav="1"]').disabled = isToday; $('#historySummary').textContent = entry ? `${completedCount} habits recorded. Reflection: “${entry}”` : completedCount ? `${completedCount} habit${completedCount === 1 ? '' : 's'} recorded for this day. Edit anything you missed.` : 'No habits have been recorded for this day yet.'; $('#historyList').innerHTML = data.routines.map((routine) => { const habits = routine.habits.filter((habit) => !habit.archived); return `<article class="history-routine"><h3>${escapeHTML(routine.name)}<span>${habits.length} habits</span></h3>${habits.map((habit) => { const checked = completed.has(habit.id); const frequency = habit.schedule.type === 'weekly' ? `${weeklyCount(habit, historyDate)} / ${habit.schedule.target} this week · flexible` : 'Daily habit'; const reflectionAction = habit.id === 'reflect' ? `<button class="reflection-entry" data-reflection-entry="history">${entry ? 'Edit reflection' : 'Write reflection'}</button>` : ''; return `<div class="history-habit ${checked ? 'done' : ''}"><button data-history-habit="${habit.id}" aria-label="Toggle ${escapeHTML(habit.name)} for ${key}">${checked ? '✓' : ''}</button><div><strong>${escapeHTML(habit.name)}</strong><p>${frequency}</p>${reflectionAction}</div><span>+${habit.points}</span></div>`; }).join('')}</article>`; }).join(''); }
function showView(view) { currentView = view; $('#todayView').hidden = view !== 'today'; $('#historyView').hidden = view !== 'history'; $('#insightsView').hidden = view !== 'insights'; document.querySelectorAll('[data-view]').forEach((button) => button.classList.toggle('active', button.dataset.view === view)); if (view === 'insights') renderInsights(); if (view === 'history') renderHistory(); }
function render() { renderHeader(); renderWeek(); renderRoutines(); renderManager(); renderArchived(); renderReflection(); renderInsights(); renderHistory(); save(); }
function populateRoutineOptions(selected) { $('#habitRoutine').innerHTML = `${data.routines.map((routine) => `<option value="${routine.id}" ${routine.id === selected ? 'selected' : ''}>${escapeHTML(routine.name)}</option>`).join('')}<option value="new">+ Create a new routine</option>`; }
function openHabitForm(id) { const item = id && allHabits(true).find((habit) => habit.id === id); $('#habitForm').reset(); $('#editHabitId').value = item?.id || ''; $('#formKicker').textContent = item ? 'EDIT HABIT' : 'NEW HABIT'; $('#formTitle').textContent = item ? 'Refine your rhythm.' : 'Build a new rhythm.'; populateRoutineOptions(item?.routine.id || data.routines[0]?.id); $('#habitName').value = item?.name || ''; $('#habitPoints').value = String(item?.points || 15); $(`input[name="schedule"][value="${item?.schedule.type || 'weekly'}"]`).checked = true; $('#weeklyTarget').value = String(item?.schedule.target || 3); $('#newRoutineField').hidden = true; $('#goalControl').hidden = (item?.schedule.type || 'weekly') !== 'weekly'; $('#habitModal').showModal(); setTimeout(() => $('#habitName').focus(), 20); }
function closeModal(id) { $(`#${id}`).close(); }
function findHabit(id) { return allHabits(true).find((habit) => habit.id === id); }
function sourceHabit(id) { for (const routine of data.routines) { const habit = routine.habits.find((item) => item.id === id); if (habit) return { habit, routine }; } return null; }
function updateScheduleUI() { const type = document.querySelector('input[name="schedule"]:checked').value; $('#goalControl').hidden = type !== 'weekly'; document.querySelectorAll('.choice').forEach((label) => label.classList.toggle('active', label.querySelector('input').checked)); }
document.addEventListener('click', (event) => { const reflectionEntry = event.target.closest('[data-reflection-entry]'); if (reflectionEntry) { openReflection(reflectionEntry.dataset.reflectionEntry === 'history' ? historyDate : today); return; }
  const habitButton = event.target.closest('[data-habit]'); if (habitButton) { const id = habitButton.dataset.habit; const completed = todayCompleted(); if (id === 'reflect' && !completed.has(id)) { openReflection(today); return; } const habit = findHabit(id); if (completed.has(id)) { completed.delete(id); data.points = Math.max(0, data.points - habit.points); showToast(`${habit.name} moved back to your list`); } else { completed.add(id); data.points += habit.points; showToast(`+${habit.points} points · Nice work!`); } data.completed[todayKey] = [...completed]; render(); }
  const historyHabit = event.target.closest('[data-history-habit]'); if (historyHabit) { const id = historyHabit.dataset.historyHabit; const key = dateKey(historyDate); const completed = completedFor(key); if (id === 'reflect' && !completed.has(id)) { openReflection(historyDate); return; } const habit = findHabit(id); if (completed.has(id)) { completed.delete(id); data.points = Math.max(0, data.points - habit.points); showToast(`${habit.name} removed from ${historyDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`); } else { completed.add(id); data.points += habit.points; showToast(`+${habit.points} points added to ${historyDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`); } data.completed[key] = [...completed]; render(); }
  const dateMove = event.target.closest('[data-history-nav]'); if (dateMove && !dateMove.disabled) { const next = new Date(historyDate); next.setDate(next.getDate() + Number(dateMove.dataset.historyNav)); if (next <= today) { historyDate = next; renderHistory(); } }
  const routineButton = event.target.closest('[data-routine]'); if (routineButton && !routineButton.disabled) { const routine = data.routines.find((item) => item.id === routineButton.dataset.routine); const rewardKey = `${todayKey}-${routine.id}-bonus`; if (!data[rewardKey]) { data.points += routine.bonus; data[rewardKey] = true; showToast(`+${routine.bonus} points · ${routine.name} complete!`); render(); } }
  const close = event.target.closest('[data-close]'); if (close) closeModal(close.dataset.close);
  const edit = event.target.closest('[data-edit]'); if (edit) { closeModal('managerModal'); openHabitForm(edit.dataset.edit); }
  const archive = event.target.closest('[data-archive]'); if (archive) { const record = sourceHabit(archive.dataset.archive); if (!record) return; record.habit.archived = true; showToast(`${record.habit.name} archived`); render(); }
  const archiveRoutine = event.target.closest('[data-archive-routine]'); if (archiveRoutine) { const routine = data.routines.find((item) => item.id === archiveRoutine.dataset.archiveRoutine); if (!routine) return; routine.archived = true; showToast(`${routine.name} and its habits archived`); render(); }
  const restore = event.target.closest('[data-restore-id]'); if (restore) { if (restore.dataset.restoreType === 'routine') { const routine = data.routines.find((item) => item.id === restore.dataset.restoreId); if (routine) { routine.archived = false; showToast(`${routine.name} restored`); } } else { const record = sourceHabit(restore.dataset.restoreId); if (record) { record.habit.archived = false; showToast(`${record.habit.name} restored`); } } render(); }
});
$('#openHabitForm').addEventListener('click', () => openHabitForm()); $('#managerAdd').addEventListener('click', () => { closeModal('managerModal'); openHabitForm(); }); $('#openManager').addEventListener('click', () => { renderManager(); $('#managerModal').showModal(); }); $('#habitRoutine').addEventListener('change', (event) => { $('#newRoutineField').hidden = event.target.value !== 'new'; }); document.querySelectorAll('input[name="schedule"]').forEach((input) => input.addEventListener('change', updateScheduleUI));
$('#habitForm').addEventListener('submit', (event) => { event.preventDefault(); const name = $('#habitName').value.trim(); if (!name) return; const selectedRoutine = $('#habitRoutine').value; let routine = data.routines.find((item) => item.id === selectedRoutine); if (selectedRoutine === 'new') { const routineName = $('#newRoutineName').value.trim(); if (!routineName) { $('#newRoutineName').focus(); showToast('Give your new routine a name'); return; } routine = { id: `routine-${Date.now()}`, name: routineName, icon: '✦', color: colors[data.routines.length % colors.length], bonus: 20, habits: [] }; data.routines.push(routine); }
  const scheduleType = document.querySelector('input[name="schedule"]:checked').value; const payload = { name, note: scheduleType === 'daily' ? 'A gentle daily practice' : 'Complete it on any days you choose', points: Number($('#habitPoints').value), schedule: scheduleType === 'weekly' ? { type: 'weekly', target: Number($('#weeklyTarget').value) } : { type: 'daily' }, archived: false }; const existingId = $('#editHabitId').value; if (existingId) { const existing = findHabit(existingId); const oldRoutine = existing.routine; const actual = oldRoutine.habits.find((habit) => habit.id === existingId); Object.assign(actual, payload); if (oldRoutine.id !== routine.id) { oldRoutine.habits = oldRoutine.habits.filter((habit) => habit.id !== existingId); routine.habits.push(actual); } showToast('Habit updated'); } else { routine.habits.push({ id: `habit-${Date.now()}`, ...payload }); showToast('New habit added to your rhythm'); } closeModal('habitModal'); render(); });
$('#openReflection').addEventListener('click', () => openReflection(today)); $('#reflectionForm').addEventListener('submit', (event) => { event.preventDefault(); const text = $('#reflectionText').value.trim(); if (!text) return; const key = $('#reflectionModal').dataset.date; data.reflections[key] = text; const reflectionHabit = findHabit('reflect'); const completed = completedFor(key); if (reflectionHabit && !completed.has('reflect')) { completed.add('reflect'); data.completed[key] = [...completed]; data.points += reflectionHabit.points; } closeModal('reflectionModal'); showToast('Reflection saved'); render(); }); $('#openDataControls').addEventListener('click', () => { renderArchived(); $('#dataModal').showModal(); }); $('#exportData').addEventListener('click', () => { const payload = JSON.stringify({ app: 'Rhythm', exportedAt: new Date().toISOString(), data }, null, 2); const href = URL.createObjectURL(new Blob([payload], { type: 'application/json' })); const link = document.createElement('a'); link.href = href; link.download = `rhythm-backup-${todayKey}.json`; link.click(); URL.revokeObjectURL(href); showToast('Backup downloaded'); }); $('#importData').addEventListener('change', async (event) => { const file = event.target.files[0]; if (!file) return; try { const imported = JSON.parse(await file.text()); const next = imported.data || imported; if (!Array.isArray(next.routines) || typeof next.completed !== 'object') throw new Error('Invalid file'); if (!window.confirm('Replace the current browser data with this backup?')) return; data = next; normalize(); render(); showToast('Backup restored'); } catch { showToast('That backup file could not be read'); } finally { event.target.value = ''; } }); $('#resetData').addEventListener('click', () => { if (!window.confirm('Reset all local data and restore the sample habits? This cannot be undone unless you exported a backup.')) return; data = JSON.parse(JSON.stringify(defaultData)); normalize(); render(); showToast('Sample data restored'); }); $('#menuButton').addEventListener('click', () => $('.sidebar').classList.toggle('open')); $('#helpButton').addEventListener('click', () => showToast('Flexible goals count any completed days before the week ends.')); render();
document.querySelectorAll('[data-view]').forEach((button) => button.addEventListener('click', () => { showView(button.dataset.view); $('.sidebar').classList.remove('open'); }));
